site_name: 'Documentation Template'
repo_url: https://github.com/harness-idp-sandbox/morningstar-java-test-neel
edit_uri: https://github.com/harness-idp-sandbox/morningstar-java-test-neel/blob/main/docs/index.md

nav:
  - Home: index.md

plugins:
  - techdocs-core